# ❌ disabled rules
disabled_rules:
  - discouraged_object_literal
  - discouraged_optional_collection
  - empty_enum_arguments
  - empty_xctest_method
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_type_interface
  - explicit_top_level_acl
  - extension_access_modifier
  - fallthrough
  - file_header
  - indentation_width
  - is_disjoint
  - let_var_whitespace
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - notification_center_detachment
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - prefixed_toplevel_constant
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_super_call
  - raw_value_for_camel_cased_codable_enum
  - required_deinit
  - required_enum_case
  - superfluous_disable_command
  - switch_case_on_newline
  - todo
  - trailing_comma
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces


# ✅ enabled additional rules
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - explicit_self
  - fatal_error_message
  - file_name
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition


# 📚 rules definitions

anyobject_protocol: warning
array_init: warning
attributes:
  severity: warning
  always_on_same_line:
    - "@IBAction"
    - "@NSManaged"
  always_on_line_above:
block_based_kvo: warning
class_delegate_protocol: error
closing_brace: warning
closure_body_length:
  warning: 60
  error: 80
closure_end_indentation: warning
closure_parameter_position: warning
closure_spacing: warning
collection_alignment:
  severity: warning
  align_colons: false
colon:
  severity: warning
  flexible_right_spacing: false
  apply_to_dictionaries: true
comma: warning
compiler_protocol_init: warning
conditional_returns_on_newline:
  severity: warning
  if_only: true
contains_over_filter_count: error
contains_over_filter_is_empty: error
contains_over_first_not_nil: error
contains_over_range_nil_comparison: error
control_statement: warning
convenience_type: error
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false
deployment_target:
  severity: warning
  iOS_deployment_target: 10.0
discarded_notification_center_observer: error
discouraged_direct_init:
  severity: error
discouraged_optional_boolean: warning
duplicate_enum_cases: error
duplicate_imports: warning
dynamic_inline: warning
empty_collection_literal: error
empty_count:
  severity: error
  only_after_dot: false
empty_parameters: warning
empty_parentheses_with_trailing_closure: warning
empty_string: error
enum_case_associated_values_count:
  warning: 2
  error: 4
expiring_todo:
  approaching_expiry_severity: warning
  reached_or_passed_expiry_severity: error
explicit_init: warning
explicit_self: warning
fatal_error_message: warning
file_length:
  warning: 400
  error: 600
  ignore_comment_only_lines: false
file_name:
  severity: warning
  excluded: [“main.swift”]
  prefixPattern:
  suffixPattern:
  nestedTypeSeparator: .
file_name_no_space:
  severity: error
  exclude: []
file_types_order:
  severity: warning
  order:
    - [SwiftLintFramework.FileType.supportingType]
    - [SwiftLintFramework.FileType.mainType]
    - [SwiftLintFramework.FileType.extension]
first_where: error
flatmap_over_map_reduce: warning
for_where: warning
force_cast: error
force_try: error
force_unwrapping: error
function_body_length:
  warning: 40
  error: 100
function_default_parameter_at_end: warning
function_parameter_count:
  warning: 4
  error: 6
  ignores_default_parameters: true
generic_type_name:
  severity: warning
  min_length: 1
  max_length: 20
  excluded: []
  allowed_symbols: []
  validates_start_with_lowercase: true
identical_operands: warning
identifier_name:
  severity: warning
  min_length: 3
  max_length: 40
  excluded:
    - id
    - URL
    - at
    - r
    - db
    - to
  allowed_symbols: []
  validates_start_with_lowercase: true
implicit_getter: warning
implicit_return:
  severity: warning
  included:
    - getter
    - closure
    - function
implicitly_unwrapped_optional:
  severity: warning
  mode: all_except_iboutlets
inert_defer: warning
joined_default_parameter: warning
large_tuple:
  warning: 4
  error: 6
last_where: warning
leading_whitespace: warning
legacy_cggeometry_functions: warning
legacy_constant: warning
legacy_constructor: warning
legacy_hashing: warning
legacy_multiple: warning
legacy_nsgeometry_functions: warning
legacy_random: warning
line_length:
  warning: 160
  error: 200
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: false
  ignores_interpolated_strings: true
literal_expression_end_indentation: warning
lower_acl_than_parent: warning
mark: warning
missing_docs:
  warning:
    - open
    - public
modifier_order:
  severity: warning
  preferred_modifier_order:
    - override
    - acl
    - setterACL
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned
multiline_arguments:
  severity: warning
  first_argument_location: any_line
  only_enforce_after_first_closure_on_first_line: false
multiline_function_chains: warning
multiline_parameters: warning
multiple_closures_with_trailing_closure: warning
nesting:
  severity: warning
  type_level: 1
  statement_level: 3
nimble_operator: warning
no_extension_access_modifier: error
no_fallthrough_only: warning
no_grouping_extension: error
no_space_in_method_call: warning
number_separator:
  severity: warning
  minimum_length: 5
object_literal:
  severity: warning
  image_literal: true
  color_literal: true
opening_brace: warning
operator_usage_whitespace: warning
operator_whitespace: warning
optional_enum_case_matching: warning
orphaned_doc_comment: warning
overridden_super_call:
  severity: error
  excluded: [[]]
  included: [["*"]]
override_in_extension: error
pattern_matching_keywords: warning
prefer_self_type_over_type_of_self: warning
private_action: error
private_outlet:
  severity: error
  allow_private_set: false
private_over_fileprivate:
  severity: warning
  validate_extensions: false
protocol_property_accessors_order: warning
quick_discouraged_call: warning
quick_discouraged_focused_test: warning
quick_discouraged_pending_test: warning
reduce_boolean: error
reduce_into: error
redundant_discardable_let: warning
redundant_nil_coalescing: warning
redundant_objc_attribute: warning
redundant_optional_initialization: warning
redundant_set_access_control: warning
redundant_string_enum_value: warning
redundant_type_annotation: warning
redundant_void_return: warning
return_arrow_whitespace: warning
shorthand_operator: warning
single_test_class: error
sorted_first_last: error
sorted_imports: warning
statement_position:
  severity: error
  statement_mode: default
static_operator: error
strict_fileprivate: warning
strong_iboutlet: error
switch_case_alignment:
  severity: warning
  indented_cases: false
syntactic_sugar: warning
toggle_bool: warning
trailing_closure:
  severity: warning
  only_single_muted_parameter: false
trailing_newline: warning
trailing_semicolon: warning
trailing_whitespace:
  severity: warning
  ignores_empty_lines: false
  ignores_comments: true
type_body_length:
  warning: 200
  error: 350
type_contents_order:
  severity: warning
  order:
    - [SwiftLintFramework.TypeContent.case]
    - [SwiftLintFramework.TypeContent.typeAlias, SwiftLintFramework.TypeContent.associatedType]
    - [SwiftLintFramework.TypeContent.subtype]
    - [SwiftLintFramework.TypeContent.typeProperty]
    - [SwiftLintFramework.TypeContent.instanceProperty]
    - [SwiftLintFramework.TypeContent.ibInspectable]
    - [SwiftLintFramework.TypeContent.ibOutlet]
    - [SwiftLintFramework.TypeContent.initializer]
    - [SwiftLintFramework.TypeContent.deinitializer]
    - [SwiftLintFramework.TypeContent.viewLifeCycleMethod]
    - [SwiftLintFramework.TypeContent.subscript]
    - [SwiftLintFramework.TypeContent.typeMethod]
    - [SwiftLintFramework.TypeContent.ibAction]
    - [SwiftLintFramework.TypeContent.otherMethod]
type_name:
  severity: warning
  min_length: 3
  max_length: 40
  excluded: []
  allowed_symbols: []
  validates_start_with_lowercase: true
unavailable_function: warning
unneeded_break_in_switch: warning
unneeded_parentheses_in_closure_argument: warning
unowned_variable_capture: error
untyped_error_in_catch: warning
unused_capture_list: error
unused_closure_parameter: warning
unused_control_flow_label: warning
unused_declaration:
  severity: error
  include_public_and_open: false
unused_enumerated: error
unused_import:
  severity: error
  require_explicit_imports: false
  allowed_transitive_imports: []
unused_optional_binding:
  severity: error
  ignore_optional_try: false
unused_setter_value: error
valid_ibinspectable: error
vertical_parameter_alignment: warning
vertical_parameter_alignment_on_call: warning
vertical_whitespace:
  severity: warning
  max_empty_lines: 2
void_return: warning
weak_delegate: error
xct_specific_matcher: warning
xctfail_message: warning
yoda_condition: warning


# 💾 List of Sources to inspect

included: # paths to include during linting. `--path` is ignored if present.
  - Cinemagic


reporter: "xcode"
